Wip/release prep (#83)
* start refactoring of json and yaml imports. move to modul

* add yaml support to ymac

* yamc: add file load handling

* yacl: start development

* yacl: rework loading paths

* yacl: migration and savable added

* rework of path reading. remove gjson workaround

* fix for not working yaml config reference

* rename asset method. added comments

* dos2unix command check added

* more tests and some fixes

* yacl: update readme and comment

* yacl: clean-code. add comments

* yacl: spel checks

diff --git a/.contxt.yml b/.contxt.yml
--- a/.contxt.yml
+++ b/.contxt.yml
@@ -75,7 +75,17 @@ task:
     require:
       system: linux
     script:
-      - find . -type f -print0 | xargs -0 dos2unix
+      - |
+       if ! [ -x "$(command -v dos2unix)" ];
+       then
+         echo ""
+         echo "<b:yellow><f:red> ERROR </>  <f:cyan>dos2unix</> is required"
+         echo ""
+       else         
+         find . -type f -print0 | xargs -0 dos2unix -v
+         git status -s
+       fi
+       
 
   ##### module based task #####
   ##### the definition for modules is stored in .modules.yml
